### ISSUE TITLE
Custom inheritance order?

### ISSUE THREAD

**Issue by mnestor** [stephenmcd/django-overextends#13]
Not sure if this is an issue or I'm just not seeing it.

I've got 3 apps that inhert from each other in the database

BaseType  #template basetype/details.html doesn't extend anything
  Type1(BaseType)  #template basetype/details.html overextends basetype/details.html
    SubType1(Type1)   #template basetype/details.html overextends basetype/details.html

Fails DB creation, works for overextends
INSTALLED_APPS (
  SubType1,
  Type1,
  BaseType, )

Works for DB creation, fails for overextends. Will only see the template from BaseType
INSTALLED_APPS (
  BaseType,
  SubType1,
  Type1, )

Perhaps this is an odd case since the URL I load is for BaseType. BaseType is constructed in such a way as to use model-utils.InhertianceManager and load the correct subclass model for the display.

**Comment by stephenmcd** [comment]
The app order will certainly affect how template inheritance works, that's intentional.

I don't think what you've loosely described is an issue with this library.

Good luck!
