### ISSUE TITLE
ImportError raised loading overextends.templatetags.overextends_tags: cannot import name find_template_loader

### ISSUE THREAD

**Issue by witalobenicio** [stephenmcd/django-overextends#18]
Im not able to use overextends in my project. Im getting this error. Any solution?

**Comment by stephenmcd** [comment]
This is already fixed in the git version, you could specify it as your dependency.

**Comment by chadsaun** [comment]
@stephenmcd - How would I specify the git version as my dependency if I've installed overextends via pip?

**Comment by jleclanche** [comment]
@stephenmcd This is blocking compatibility with django 1.8. Could you make a new release?

**Comment by stephenmcd** [comment]
Need to resolve #16 first, want to take a look?

**Comment by jleclanche** [comment]
I can take a look at it tomorrow, yes, but no guarantees.
