### ISSUE TITLE
Support Django 1.9

### ISSUE THREAD

**Issue by vinnyrose** [stephenmcd/django-overextends#19]
`add_to_builtins` is deprecated and will be removed in 1.9.
https://docs.djangoproject.com/en/dev/releases/1.9/#django-template-base-add-to-builtins-is-removed

Must use a setting, so probably going to need a note in docs and a runtime warning? e.g. (not tested)

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'APP_DIRS': True,
            'OPTIONS': {
                'builtins': ['overextends.templatetags.overextends_tags'],
            }
        },
    ]

**Comment by stephenmcd** [comment]
Sounds good. Want to set up a PR with the change? Thank you.

**Comment by stephenmcd** [comment]
0a1d70fb1238e39adba258486aac892e7f9b9448

**Comment by diox** [comment]
Django 1.9 was released today. Could you please release a new version with this fix ? This would unblock django-compressor tests, which depend on overextends for some specific usage scenarios. See https://github.com/django-compressor/django-compressor/pull/697

Thanks!

**Comment by stephenmcd** [comment]
See #23
